package aws

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
)

// managedProfilesMu serializes managed-profile writes within this process; the
// advisory file lock acquireConfigLock takes serializes them across processes.
// Together they make the read-modify-write of ~/.aws/config atomic against a
// concurrent generation for another alias (a launcher probe and a serve
// subprocess, or two AWS sources, all write the same file).
var managedProfilesMu sync.Mutex

// profileName is the AWS_PROFILE for one configured account: a deterministic
// triagent-cloud-<alias>-<account_id> so the server's ActiveTargetEnv and the
// generated ~/.aws/config block name the same profile. Exported for reuse by the
// launcher-side env builders, which must pin the same profile the provider
// generated.
func ProfileName(alias, accountID string) string {
	return profileName(alias, accountID)
}

func profileName(alias, accountID string) string {
	return "triagent-cloud-" + alias + "-" + accountID
}

// blockMarkers returns the BEGIN/END comment lines delimiting one alias's
// managed section in ~/.aws/config, so a rewrite replaces exactly that block and
// never touches operator-authored profiles or another alias's block.
func blockMarkers(alias string) (begin, end string) {
	return "# BEGIN triagent-cloud-" + alias, "# END triagent-cloud-" + alias
}

// managedSentinel separates the verbatim copy of the operator's config (above)
// from triagent's generated assume-role profiles (below) in the target file.
const managedSentinel = "# ===== triagent-managed cloud profiles (generated by triagent; do not edit) ====="

// writeManagedProfiles regenerates the triagent-owned AWS config at targetPath
// from the operator's config at sourcePath, never editing the operator's file.
// The target is a copy of the operator config (with any triagent-managed blocks
// stripped) followed by managedSentinel and one [profile
// triagent-cloud-<alias>-<account_id>] block per account, each layering its
// role_arn over sourceProfile. Copying the operator config keeps source_profile
// resolvable; triagent holds no credential — the aws CLI performs the
// assume-role at run time. The managed region accumulates one block per alias,
// so rewriting one alias preserves the others. Serialized across processes by an
// advisory lock on targetPath and written tmp-file-then-rename; it refuses to
// write output the aws CLI could not parse.
func writeManagedProfiles(targetPath, sourcePath, alias, sourceProfile string, accounts []Account) error {
	begin, end := blockMarkers(alias)

	var block strings.Builder
	block.WriteString(begin)
	block.WriteString("\n")
	for _, a := range accounts {
		fmt.Fprintf(&block, "[profile %s]\n", profileName(alias, a.ID))
		fmt.Fprintf(&block, "role_arn       = %s\n", a.RoleARN)
		fmt.Fprintf(&block, "source_profile = %s\n", sourceProfile)
	}
	block.WriteString(end)
	block.WriteString("\n")

	managedProfilesMu.Lock()
	defer managedProfilesMu.Unlock()

	if err := os.MkdirAll(filepath.Dir(targetPath), 0o700); err != nil {
		return fmt.Errorf("aws: create config dir for %s: %w", targetPath, err)
	}
	release, err := acquireConfigLock(targetPath)
	if err != nil {
		return err
	}
	defer release()

	base, err := os.ReadFile(sourcePath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("aws: read operator config %s: %w", sourcePath, err)
	}
	existing, err := os.ReadFile(targetPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("aws: read managed config %s: %w", targetPath, err)
	}

	managed := replaceBlock(managedRegion(string(existing)), begin, end, block.String())
	merged := assembleManagedConfig(stripManagedBlocks(string(base)), managed)
	// Fail closed: never land content the aws CLI cannot parse. A single stray
	// line breaks every profile in the file, so refuse rather than write —
	// surfacing the offending line instead of a downstream "sts ... failed".
	if bad := firstInvalidConfigLine(merged); bad != "" {
		return fmt.Errorf("aws: refusing to write %s: line %q is not valid config (expected a [section], comment, or key=value); fix the operator config %s and retry", targetPath, bad, sourcePath)
	}
	return atomicWrite(targetPath, []byte(merged))
}

// managedRegion returns the generated region of a prior target config:
// everything after managedSentinel, or "" when absent (or when reading the
// operator's own config, which never carries the sentinel).
func managedRegion(content string) string {
	i := strings.Index(content, managedSentinel)
	if i < 0 {
		return ""
	}
	return strings.TrimPrefix(content[i+len(managedSentinel):], "\n")
}

// stripManagedBlocks removes every # BEGIN/# END triagent-cloud-* region from
// content, so the operator-config copy never carries a managed block into the
// region above the sentinel — which would duplicate the managed region below it.
// Operator configs normally have none; this keeps the generated file clean if
// one is present.
func stripManagedBlocks(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	skipping := false
	for _, ln := range lines {
		t := strings.TrimSpace(ln)
		switch {
		case !skipping && strings.HasPrefix(t, "# BEGIN triagent-cloud-"):
			skipping = true
		case skipping && strings.HasPrefix(t, "# END triagent-cloud-"):
			skipping = false
		case !skipping:
			out = append(out, ln)
		}
	}
	return strings.Join(out, "\n")
}

// assembleManagedConfig joins the (stripped) operator base and the managed
// region under the sentinel. The result always ends with a newline.
func assembleManagedConfig(base, managed string) string {
	var b strings.Builder
	if base = strings.TrimRight(base, "\n"); base != "" {
		b.WriteString(base)
		b.WriteString("\n\n")
	}
	b.WriteString(managedSentinel)
	b.WriteString("\n")
	if managed = strings.TrimLeft(managed, "\n"); managed != "" && !strings.HasSuffix(managed, "\n") {
		managed += "\n"
	}
	b.WriteString(managed)
	return b.String()
}

// acquireConfigLock takes an exclusive advisory lock on a sibling lock file so
// the read-modify-write below is atomic across processes. It returns a release
// func that unlocks and closes the lock file; the lock file itself is left in
// place (an empty marker), never the config.
func acquireConfigLock(configPath string) (func(), error) {
	lockPath := configPath + ".lock"
	f, err := os.OpenFile(lockPath, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, fmt.Errorf("aws: open config lock %s: %w", lockPath, err)
	}
	if err := lockExclusive(f); err != nil {
		_ = f.Close()
		return nil, fmt.Errorf("aws: lock config %s: %w", lockPath, err)
	}
	return func() {
		_ = unlockFile(f)
		_ = f.Close()
	}, nil
}

// replaceBlock splices block in place of any existing begin..end region in
// content, appending it (after a separating blank line) when no prior block is
// present. Lines outside the region are preserved verbatim, so operator-authored
// profiles survive.
func replaceBlock(content, begin, end, block string) string {
	bIdx := strings.Index(content, begin)
	if bIdx < 0 {
		if content == "" {
			return block
		}
		if !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		return content + "\n" + block
	}
	eIdx := strings.Index(content[bIdx:], end)
	if eIdx < 0 {
		// Truncated prior block (no END): replace from BEGIN to end of file.
		return content[:bIdx] + block
	}
	tailStart := bIdx + eIdx + len(end)
	tail := content[tailStart:]
	tail = strings.TrimPrefix(tail, "\n")
	return content[:bIdx] + block + tail
}

// firstInvalidConfigLine returns the first structurally-invalid line in an
// ~/.aws/config body, or "" when every line is valid. Used to fail closed
// before writing: the aws CLI rejects the whole file if any line is not blank,
// a comment, a [section] header, or a key=value (which also covers the indented
// sub-keys AWS uses for nested settings).
func firstInvalidConfigLine(content string) string {
	for _, ln := range strings.Split(content, "\n") {
		t := strings.TrimSpace(ln)
		switch {
		case t == "":
		case strings.HasPrefix(t, "#"), strings.HasPrefix(t, ";"):
		case strings.HasPrefix(t, "[") && strings.HasSuffix(t, "]"):
		case strings.Contains(t, "="):
		default:
			return t
		}
	}
	return ""
}

// atomicWrite writes body to dst via a sibling tmp file then renames it into
// place, so a reader never observes a partially written ~/.aws/config.
func atomicWrite(dst string, body []byte) error {
	if err := os.MkdirAll(filepath.Dir(dst), 0o700); err != nil {
		return fmt.Errorf("aws: create config dir for %s: %w", dst, err)
	}
	tmp := dst + ".tmp." + strconv.Itoa(os.Getpid())
	if err := os.WriteFile(tmp, body, 0o600); err != nil {
		return fmt.Errorf("aws: write config tmp %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, dst); err != nil {
		return fmt.Errorf("aws: rename config %s: %w", dst, err)
	}
	return nil
}
